# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symmemory < Formula
  desc "Persistent memory layer and semantic knowledge base for AI agents"
  homepage "https://github.com/danieljustus/symaira-memory"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.2.0/symmemory_darwin_x86_64.tar.gz"
      sha256 "bd522aff740f4b3fac26c79896f07e6222f698ebad0f3da81649e344ff48a9b4"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.2.0/symmemory_darwin_arm64.tar.gz"
      sha256 "d52adba24a72affec86ceb26738f5383e4f9f0e854a061a4ef16ec273e91c00f"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.2.0/symmemory_linux_x86_64.tar.gz"
      sha256 "e5dceb8d6168a653f779bad5ec88cc01f94080e9972314699c938709bfdb3630"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.2.0/symmemory_linux_arm64.tar.gz"
      sha256 "7f2463fdb69a84919f9e364be48ea16a7281276b426bb46b34077214133ce983"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  test do
    system "#{bin}/symmemory", "version"
  end
end
