# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvibe < Formula
  desc "Graphical Vibe-Coding Baukasten that drives opencode"
  homepage "https://github.com/danieljustus/symaira-vibecoder"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.4.0/symvibe_0.4.0_darwin_amd64.tar.gz"
      sha256 "c6caa741ff1ef9817450d894f0a3a9142a5000b7d2b483af9eb35a58fc78539b"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.4.0/symvibe_0.4.0_darwin_arm64.tar.gz"
      sha256 "c7e65ea19b503ada721b7dafa869d8761c502a5a0baf0d5753e5ec9fbdd394b1"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.4.0/symvibe_0.4.0_linux_amd64.tar.gz"
      sha256 "fc1cf6bdc71d363c44022736060fbd7e5b438950b007660d3fdedea691558c1b"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.4.0/symvibe_0.4.0_linux_arm64.tar.gz"
      sha256 "1dc6d7d7ef66f74625308bd015c374d377221eacef82e8dbeb08d3e5353d0e42"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  test do
    system "#{bin}/symvibe", "version"
  end
end
