# This file was generated by GoReleaser. DO NOT EDIT.
cask "symseek" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "d9bd122d73224dfe59afb6a7bd677ca08663f6753fc79505fb39d135aefa61a2"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3ba302c9044cc277a1ddda4f1fbb982cffa67c211392311fde7f6f513d96b83"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddbc2265956a73d6e7f3899bdf37a26765df782b9f61019896a3fb1517a1b858"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31d9e41053997df31f4a4149a976e3b59c585c2910859d64d16ec60b618ccf65"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_arm64.tar.gz"
    end
  end

  name "symseek"
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symseek"

  # No zap stanza required

end
