# This file was generated by GoReleaser. DO NOT EDIT.
cask "symseek" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "25db16d37f0a596269c06f092ab8a2c09f4eed94a20087dbbf1f4e7c9a4c1175"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92b8c85a9e54227f4a8d09081ff6e46be69fb88f0e4d03466f562a4c8348f630"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b1b838b7561433847e0ba00f3e52759f1d36887e2201a6d4eca8aed9e1624052"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "320031ed524d4991dcfeba200302d5d2b7516d0afcc26de2c9662232ad07e879"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_arm64.tar.gz"
    end
  end

  name "symseek"
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symseek"

  # No zap stanza required

end
