# This file was generated by GoReleaser. DO NOT EDIT.
cask "symseek" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "fe94902aaaf5e67c86f3e40cb22e99cfaf2a873e770fb5c67b5b254837eebe5d"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d01553e08ae2b8e14d5c3339e2ae24a024eef635f63a5f828f801740e3a24e71"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c9df922daa8a0e5ecf1b0861eb7169734e4c6493c05548bcb6de84b7d863caf"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6178b9ae753d81f4c7b508bb19c3309fdccdea46eebcdeaf28ab7ac49e212700"
      url "https://github.com/danieljustus/symaira-seek/releases/download/v#{version}/symaira-seek_#{version}_linux_arm64.tar.gz"
    end
  end

  name "symseek"
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "symseek"

  # No zap stanza required

end
