# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpass < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/OpenPass"
  version "2.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.8.2/OpenPass_2.8.2_darwin_amd64.tar.gz"
      sha256 "5e525cad4e8ee9643a9cceceffff836946aa9ff134fc15be71e96fbde75a7e42"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.8.2/OpenPass_2.8.2_darwin_arm64.tar.gz"
      sha256 "0e795e49a8af7f37aa6e9e3c981ca75e7bd49fd5ac85b30c92c4467f3cbb0337"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.8.2/OpenPass_2.8.2_linux_amd64.tar.gz"
      sha256 "4b6ffddf88a6f614f0ddeef7dc9da4b159557f339a4a0a63bb80ecb6ae097e04"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.8.2/OpenPass_2.8.2_linux_arm64.tar.gz"
      sha256 "28aec4a79a5f6ac55e1660e657975fe65d6bf9ebe15b6a0ddf24473020a6ffc8"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      OpenPass has been installed!

      To get started:
        openpass init                    # Initialize a new vault
        openpass set github.com/username # Add your first entry
        openpass get github.com/username # Retrieve it

      For MCP server setup:
        openpass mcp-config <name>

      Documentation: https://github.com/danieljustus/OpenPass#readme
    EOS
  end

  test do
    system "#{bin}/openpass", "version"
  end
end
