# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpass < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/OpenPass"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.0.0/OpenPass_2.0.0_darwin_amd64.tar.gz"
      sha256 "0cc473e97f42e795838cd23b936b6d5780f5eb912a2b00b7940cc96b82b8437b"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.0.0/OpenPass_2.0.0_darwin_arm64.tar.gz"
      sha256 "67152414f8c8bc447de57e491edbee93e78513fb74451bcfc04cfb8c6762df00"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.0.0/OpenPass_2.0.0_linux_amd64.tar.gz"
      sha256 "9eb964bb276e09b208d019d119bb1d7412ab4b9ce76ccf31d8316ded2b789e46"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.0.0/OpenPass_2.0.0_linux_arm64.tar.gz"
      sha256 "4fd133120df9f789aceb0215fb34268d2ba83b593f17d138adbd332297cf39b5"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      OpenPass has been installed!

      To get started:
        openpass init                    # Initialize a new vault
        openpass set github.com/username # Add your first entry
        openpass get github.com/username # Retrieve it

      For MCP server setup:
        openpass mcp-config <name>

      Documentation: https://github.com/danieljustus/OpenPass#readme
    EOS
  end

  test do
    system "#{bin}/openpass", "version"
  end
end
