# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openpass < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/OpenPass"
  version "2.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.2.1/OpenPass_2.2.1_darwin_amd64.tar.gz"
      sha256 "fe54bd39b5589c1ae3ff4592e56252ec2fc2b15fd80b3fe05d7baa30ec74c10b"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.2.1/OpenPass_2.2.1_darwin_arm64.tar.gz"
      sha256 "0312b71782d3f75e366c0d9957c0e4b80aa58dfe150db6a888e53d62e352e8f3"

      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.2.1/OpenPass_2.2.1_linux_amd64.tar.gz"
      sha256 "ed12c82a2386ff7514efd4d57f8eda3451f3bc1ba4794b1b93267c026aa3e544"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/OpenPass/releases/download/v2.2.1/OpenPass_2.2.1_linux_arm64.tar.gz"
      sha256 "e270fae62d2d4ed77c3522916c0be6cde83392266193528fb6414927386ce70c"
      define_method(:install) do
        bin.install "openpass"
        generate_completions_from_executable(bin/"openpass", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      OpenPass has been installed!

      To get started:
        openpass init                    # Initialize a new vault
        openpass set github.com/username # Add your first entry
        openpass get github.com/username # Retrieve it

      For MCP server setup:
        openpass mcp-config <name>

      Documentation: https://github.com/danieljustus/OpenPass#readme
    EOS
  end

  test do
    system "#{bin}/openpass", "version"
  end
end
