# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symbrain < Formula
  desc "Portable agent-context layer: one MCP gateway multiplexing vault, memory, and skills for AI harnesses"
  homepage "https://github.com/danieljustus/symaira-brain"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-brain/releases/download/v0.4.0/symbrain_0.4.0_darwin_amd64.tar.gz"
      sha256 "c781cd3739857ed3423288f2c192af1c3f05f43a7469f4191eb8d3688dc8ad16"

      define_method(:install) do
        bin.install "symbrain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-brain/releases/download/v0.4.0/symbrain_0.4.0_darwin_arm64.tar.gz"
      sha256 "08539c3685d1c87537e1e560575c8ef6c21f67bf54dbfd5f59460dabdf73bd97"

      define_method(:install) do
        bin.install "symbrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-brain/releases/download/v0.4.0/symbrain_0.4.0_linux_amd64.tar.gz"
      sha256 "335771a037e12e2e97e2a4542f843c3300639c7b9df46f3f0c599ae948f98faf"
      define_method(:install) do
        bin.install "symbrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-brain/releases/download/v0.4.0/symbrain_0.4.0_linux_arm64.tar.gz"
      sha256 "1bdf9e9dcce0c226791feb6d8bf3972a6146acbf4c29b2c483609468b653e14f"
      define_method(:install) do
        bin.install "symbrain"
      end
    end
  end

  test do
    system "#{bin}/symbrain", "version"
  end
end
