# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symbrowse < Formula
  desc "Agent-operable browser automation over Chrome DevTools Protocol"
  homepage "https://github.com/danieljustus/symaira-browse"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.6.1/symbrowse_0.6.1_darwin_amd64.tar.gz"
      sha256 "b7dc9477c032013864494fa7f3e79d72718e4516978469747263f522aaddd3a5"

      define_method(:install) do
        bin.install "symbrowse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.6.1/symbrowse_0.6.1_darwin_arm64.tar.gz"
      sha256 "bce51209b148eb72b0bebc19e9ce75b105723f39983d339d44860535dc253076"

      define_method(:install) do
        bin.install "symbrowse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.6.1/symbrowse_0.6.1_linux_amd64.tar.gz"
      sha256 "17c5131b6f8ce9ecac074e104af3d258f834ad54d2a38af26ba3a42b36a6d9d6"
      define_method(:install) do
        bin.install "symbrowse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.6.1/symbrowse_0.6.1_linux_arm64.tar.gz"
      sha256 "f1b3cc7b58baacf615c9624c396dfb53df499f63dfa5c85386da4ad6cd1289b3"
      define_method(:install) do
        bin.install "symbrowse"
      end
    end
  end

  test do
    system "#{bin}/symbrowse", "version"
  end
end
