# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symbrowse < Formula
  desc "Agent-operable browser automation over Chrome DevTools Protocol"
  homepage "https://github.com/danieljustus/symaira-browse"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.4.0/symbrowse_0.4.0_darwin_amd64.tar.gz"
      sha256 "8a7f97b7301e98861e5735b6b6a7cf6da9e455715fda344e2d6563b356d55ec4"

      define_method(:install) do
        bin.install "symbrowse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.4.0/symbrowse_0.4.0_darwin_arm64.tar.gz"
      sha256 "6bba180509baaad2b564aaadc8df9d56d13d301c5bca405e8c25edc815558bb8"

      define_method(:install) do
        bin.install "symbrowse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.4.0/symbrowse_0.4.0_linux_amd64.tar.gz"
      sha256 "01076c8f4b3c928957f6ac76bdbf4969cf4e83626e949ffb24f3d64d596b5033"
      define_method(:install) do
        bin.install "symbrowse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-browse/releases/download/v0.4.0/symbrowse_0.4.0_linux_arm64.tar.gz"
      sha256 "9c16442cf32bcbbaf10ada4e6518f1b9d73a5a89e305975d929f7eeba7d8ce3c"
      define_method(:install) do
        bin.install "symbrowse"
      end
    end
  end

  test do
    system "#{bin}/symbrowse", "version"
  end
end
