# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symdesk < Formula
  desc "Local-first markdown vault workspace: CLI and MCP server"
  homepage "https://github.com/danieljustus/symaira-desktop"
  version "0.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.7.1/symaira-desktop_0.7.1_darwin_amd64.tar.gz"
      sha256 "984a81d57a6710ad5e123ab283ce207bfd7dabbe126908afc16b780f8a54a26c"

      define_method(:install) do
        bin.install "symdesk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.7.1/symaira-desktop_0.7.1_darwin_arm64.tar.gz"
      sha256 "1714191108538bcb7a70999c0db399ef5542a30a2c0162dceae342354761c023"

      define_method(:install) do
        bin.install "symdesk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.7.1/symaira-desktop_0.7.1_linux_amd64.tar.gz"
      sha256 "902ee7b82bf25b47c9e7872bdb592e89870808de3ce952497f61b8d11ee6e4a7"
      define_method(:install) do
        bin.install "symdesk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.7.1/symaira-desktop_0.7.1_linux_arm64.tar.gz"
      sha256 "a3a40341c60e266231041b7b7084bac822ef67ab2ba47e494c7c7f36f247dd35"
      define_method(:install) do
        bin.install "symdesk"
      end
    end
  end

  test do
    system "#{bin}/symdesk", "version"
  end
end
