# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symdesk < Formula
  desc "Local-first markdown vault workspace: CLI and MCP server"
  homepage "https://github.com/danieljustus/symaira-desktop"
  license "Apache-2.0"

  conflicts_with "symroom", because: "symdesk includes the symroom binary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.11.1/symaira-desktop_0.11.1_darwin_amd64.tar.gz"
      sha256 "9f557091a74eecc4c9aeb0fb280130cc32fef1230d73ad5728f8f10f636dcc28"

      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.11.1/symaira-desktop_0.11.1_darwin_arm64.tar.gz"
      sha256 "a515e2e8afd11cc3296a29dd7d4c0be18a79a1f52ea4cc7ac388f1f9d6e045db"

      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.11.1/symaira-desktop_0.11.1_linux_amd64.tar.gz"
      sha256 "74f9b041d54b0af001aaf708ae47f21442ab0f8255341122e59ac9fe8046d209"
      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.11.1/symaira-desktop_0.11.1_linux_arm64.tar.gz"
      sha256 "5d0a639896d6e47c16b31f7cff26e3c658bb5b80aad0e9c38a0d8cf10904ed66"
      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
  end

  test do
    system "#{bin}/symdesk", "version"
  end
end
