# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symdesk < Formula
  desc "Local-first markdown vault workspace: CLI and MCP server"
  homepage "https://github.com/danieljustus/symaira-desktop"
  version "0.12.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.12.2/symaira-desktop_0.12.2_darwin_amd64.tar.gz"
      sha256 "4897e8a4de91b09a699650338860c3485940d6c1d875e4ed580291722d7df02f"

      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.12.2/symaira-desktop_0.12.2_darwin_arm64.tar.gz"
      sha256 "00d9bab214e3e54f0578821622578ce489498cd6dabce810c6257bcf79d0fcc2"

      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.12.2/symaira-desktop_0.12.2_linux_amd64.tar.gz"
      sha256 "2655779e3846f19a22e6a8258f699b6af6d1e2721026cf871a9f6b6e1431b1fe"
      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-desktop/releases/download/v0.12.2/symaira-desktop_0.12.2_linux_arm64.tar.gz"
      sha256 "cc7d1dc37e22182b7dc7fbe72d9aa0c9adff490882b2121133e6f12fa35bb359"
      define_method(:install) do
        bin.install "symdesk"
        bin.install "symroom"
      end
    end
  end

  test do
    system "#{bin}/symdesk", "version"
  end
end
