# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symfritz < Formula
  desc "CLI to administer, analyse, and control an AVM FRITZ!Box"
  homepage "https://github.com/danieljustus/symaira-fritz"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.3.0/symaira-fritz_0.3.0_darwin_amd64.tar.gz"
      sha256 "bdd2f6bd3364c010391ea355ee748e035aa2c170ead52cf831e3b7303d135171"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.3.0/symaira-fritz_0.3.0_darwin_arm64.tar.gz"
      sha256 "d4903588d38e1f4351bdb65a0c30e7f872e89984078611f099fa37f499fdcc6e"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.3.0/symaira-fritz_0.3.0_linux_amd64.tar.gz"
      sha256 "25e3945cff8c0085c8b814877ad72fcb78005416eb1badd0ad9089a13c0c5f09"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.3.0/symaira-fritz_0.3.0_linux_arm64.tar.gz"
      sha256 "f28edd3a9f519c0397697c04f54818d4786fef6fc9f0aa6ad2fdeb52b69c7943"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  test do
    system "#{bin}/symfritz", "version"
  end
end
