# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symfritz < Formula
  desc "CLI to administer, analyse, and control an AVM FRITZ!Box"
  homepage "https://github.com/danieljustus/symaira-fritz"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.6.0/symaira-fritz_0.6.0_darwin_amd64.tar.gz"
      sha256 "23907360254624e9471323c24cba025b3fd532ef1e02974cfd4ec2b76d2d2ac0"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.6.0/symaira-fritz_0.6.0_darwin_arm64.tar.gz"
      sha256 "d0b8c94b5e32477163f605824a14ac34f0da044918fb9fa7394ee6af7c608b06"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.6.0/symaira-fritz_0.6.0_linux_amd64.tar.gz"
      sha256 "7a516f9489cf88485909554529080fb6ff4070c9d1ec86e42378b222af71e8f9"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.6.0/symaira-fritz_0.6.0_linux_arm64.tar.gz"
      sha256 "150c2d82f4ddefeff16fe821836681894c0cdd577f3af0ae4a02de9f639b29f8"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  test do
    system "#{bin}/symfritz", "version"
  end
end
