# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symfritz < Formula
  desc "CLI to administer, analyse, and control an AVM FRITZ!Box"
  homepage "https://github.com/danieljustus/symaira-fritz"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.1.0/symaira-fritz_0.1.0_darwin_amd64.tar.gz"
      sha256 "4cecd1711cb0ac9ec5a323ecabe1474ba1ad2b1389d353bd338d812f731e59b0"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.1.0/symaira-fritz_0.1.0_darwin_arm64.tar.gz"
      sha256 "8a926817487fdf98b360e942d57bbdbbed1c879b7b7612fb71d1ec846e561999"

      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.1.0/symaira-fritz_0.1.0_linux_amd64.tar.gz"
      sha256 "d07ebcc4dceea0eae73c588c6c7e4f9b644796d5d4e1bf3d42fef441d36dfd48"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fritz/releases/download/v0.1.0/symaira-fritz_0.1.0_linux_arm64.tar.gz"
      sha256 "58104feb619d8d52c64b4209f21069943e9cf21c544fc13185ea7bfb5512a9ba"
      define_method(:install) do
        bin.install "symfritz"
      end
    end
  end

  test do
    system "#{bin}/symfritz", "version"
  end
end
