# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symfetch < Formula
  desc "AI-native web fetch engine for LLM agents"
  homepage "https://github.com/danieljustus/symaira-fetch"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-fetch/releases/download/v0.3.0/symaira-fetch_0.3.0_darwin_amd64.tar.gz"
      sha256 "2753768027f64b1d55fe4cc95d02c6a215dec583a5b91a82c7a5bed903b23221"

      define_method(:install) do
        bin.install "symfetch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-fetch/releases/download/v0.3.0/symaira-fetch_0.3.0_darwin_arm64.tar.gz"
      sha256 "e5920c6220d0d6a5db4869d0e6a7ffcdf971dd4bbd52c2f15aebccbdc109ee8a"

      define_method(:install) do
        bin.install "symfetch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fetch/releases/download/v0.3.0/symaira-fetch_0.3.0_linux_amd64.tar.gz"
      sha256 "64999f425179b5305dc3ed3eda4e6c333bf91e9787a20ca6d1a92ce67edabc34"
      define_method(:install) do
        bin.install "symfetch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-fetch/releases/download/v0.3.0/symaira-fetch_0.3.0_linux_arm64.tar.gz"
      sha256 "c0d1627b05cc05f3e1a76e6c1d255028fa45b3ad4f2cf3c53fc500902f42440b"
      define_method(:install) do
        bin.install "symfetch"
      end
    end
  end

  test do
    system "#{bin}/symfetch", "version"
  end
end
