# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symguard < Formula
  desc "Local-first security gateway for AI agents and MCP servers"
  homepage "https://github.com/danieljustus/symaira-guard"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-guard/releases/download/v0.4.0/symaira-guard_0.4.0_darwin_amd64.tar.gz"
      sha256 "5188f812bd3f86853077c59a13fbe4af7987a1d00e0e48aab60ddd55ac96426f"

      define_method(:install) do
        bin.install "symguard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-guard/releases/download/v0.4.0/symaira-guard_0.4.0_darwin_arm64.tar.gz"
      sha256 "31396bea7ee254f1a59a9fce38331bb93f322cdc51b20790a4275ac6c02d5486"

      define_method(:install) do
        bin.install "symguard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-guard/releases/download/v0.4.0/symaira-guard_0.4.0_linux_amd64.tar.gz"
      sha256 "5f337b4bd206bcd808f36dbed546c6f2d498be8ee345e8fb07dceb1893a4646e"
      define_method(:install) do
        bin.install "symguard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-guard/releases/download/v0.4.0/symaira-guard_0.4.0_linux_arm64.tar.gz"
      sha256 "fbbb2cc4978e1dc8ddf9058b325ac233c2765c801bb29cf0fec0b8b252680717"
      define_method(:install) do
        bin.install "symguard"
      end
    end
  end

  test do
    system "#{bin}/symguard", "version"
  end
end
