# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symingest < Formula
  desc "Document ingestion + OCR pipeline for the Symaira ecosystem"
  homepage "https://github.com/danieljustus/symaira-ingest"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.9.0/symaira-ingest_0.9.0_darwin_amd64.tar.gz"
      sha256 "d16dc9c76c9b78f937dd39c2783d5204cfb16ebe7120d3d89e74ff32751a7458"

      define_method(:install) do
        bin.install "symingest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.9.0/symaira-ingest_0.9.0_darwin_arm64.tar.gz"
      sha256 "9e91e8e3b00a0a74c7ac44413748c2e281756e330dba29bb956ead4a7bd6912d"

      define_method(:install) do
        bin.install "symingest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.9.0/symaira-ingest_0.9.0_linux_amd64.tar.gz"
      sha256 "5b4f2591867248b8adfb4acab6893a369782ca4b63ffb64bb0bfb6bb84fe0f75"
      define_method(:install) do
        bin.install "symingest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.9.0/symaira-ingest_0.9.0_linux_arm64.tar.gz"
      sha256 "b7a8bd1eb7244ed640259838a21913c30e08d793a472f0a412f5e43407896cf1"
      define_method(:install) do
        bin.install "symingest"
      end
    end
  end

  test do
    system "#{bin}/symingest", "version"
  end
end
