# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symingest < Formula
  desc "Document ingestion + OCR pipeline for the Symaira ecosystem"
  homepage "https://github.com/danieljustus/symaira-ingest"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.7.0/symaira-ingest_0.7.0_darwin_amd64.tar.gz"
      sha256 "77f64272787235717893de8bac228d63e4e808e5507e2b0a81a0ff601011f328"

      define_method(:install) do
        bin.install "symingest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.7.0/symaira-ingest_0.7.0_darwin_arm64.tar.gz"
      sha256 "f44398a77746931fea556b84f7061d8aca13c4a50ef74deed489e1af61da95ff"

      define_method(:install) do
        bin.install "symingest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.7.0/symaira-ingest_0.7.0_linux_amd64.tar.gz"
      sha256 "658bbe10b3ef773ff3c07e05e5af1efd656606bc55ad268e7b4647364e3d3254"
      define_method(:install) do
        bin.install "symingest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-ingest/releases/download/v0.7.0/symaira-ingest_0.7.0_linux_arm64.tar.gz"
      sha256 "dd2c2da07d49ae4aae146edab34008ce9a11e55f7ec99ef231803a47c1afd505"
      define_method(:install) do
        bin.install "symingest"
      end
    end
  end

  test do
    system "#{bin}/symingest", "version"
  end
end
