# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symmemory < Formula
  desc "Persistent memory layer and semantic knowledge base for AI agents"
  homepage "https://github.com/danieljustus/symaira-memory"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.9.0/symmemory_darwin_x86_64.tar.gz"
      sha256 "8a0ad157f6bb08a5a3d11c84f86ab800fb5547704b0b8f61c459248ecc4b7473"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.9.0/symmemory_darwin_arm64.tar.gz"
      sha256 "86080c50f02b1b1eedf46ff2e5b20c0b3f63a5a62a6efa46467c55815d05d1b8"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.9.0/symmemory_linux_x86_64.tar.gz"
      sha256 "8845be4d26eb1a6c412d95fb9fbd522ac396269e8b776d6806803b9f0264e55a"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.9.0/symmemory_linux_arm64.tar.gz"
      sha256 "86e083b2a2d39d483d667c50d834c8f6881ad2c11778dd647b1bcb83f35bf8da"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  test do
    system "#{bin}/symmemory", "version"
  end
end
