# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symmemory < Formula
  desc "Persistent memory layer and semantic knowledge base for AI agents"
  homepage "https://github.com/danieljustus/symaira-memory"
  version "0.15.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.15.1/symmemory_darwin_x86_64.tar.gz"
      sha256 "3f6ca36acbd5be12e0ffa3bdea2220f94685d51cff3e370b9406a25beaaea28a"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.15.1/symmemory_darwin_arm64.tar.gz"
      sha256 "f86fea2ec6ac0da371839aa8707de5132c9657a18340716fa895b4144dda4668"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.15.1/symmemory_linux_x86_64.tar.gz"
      sha256 "2c755bd8467c58ca0bdf84386a7e08adab39016d69761c175092806d2d10bf2e"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.15.1/symmemory_linux_arm64.tar.gz"
      sha256 "24a894e24e8858ee244b04cc2f07531ab1d80cbe709ae65992728dd9b389b98c"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  test do
    system "#{bin}/symmemory", "version"
  end
end
