# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symmemory < Formula
  desc "Persistent memory layer and semantic knowledge base for AI agents"
  homepage "https://github.com/danieljustus/symaira-memory"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.10.0/symmemory_darwin_x86_64.tar.gz"
      sha256 "9a3e9b2ad7dc126761e4d79d4d63cfd3419d989e0b61811649ac18bddfbc0d84"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.10.0/symmemory_darwin_arm64.tar.gz"
      sha256 "17570559a9b9154b916dfd2616252bdb581b417e979c79734fb51dab4d93272a"

      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.10.0/symmemory_linux_x86_64.tar.gz"
      sha256 "792fc7785d31bb9bdf4af354c45988a5bf6b66e4a15fb2b7d0969fdf527741bb"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-memory/releases/download/v0.10.0/symmemory_linux_arm64.tar.gz"
      sha256 "b62366be6a3282a1472651fbe3f7fba6f740ef05c86afc56179e4345835aa73b"
      define_method(:install) do
        bin.install "symmemory"
      end
    end
  end

  test do
    system "#{bin}/symmemory", "version"
  end
end
