# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symprint < Formula
  desc "Markdown → beautiful PDF via named use-case profiles (Typst engine)"
  homepage "https://github.com/danieljustus/symaira-print"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.2.0/symaira-print_0.2.0_darwin_amd64.tar.gz"
      sha256 "5c961ea171b3a0cae941706d5b67d821c1a69ffa8273a37ce91a1252b0eadd16"

      define_method(:install) do
        bin.install "symprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.2.0/symaira-print_0.2.0_darwin_arm64.tar.gz"
      sha256 "13e968c6548e452c4340586fc903f8df8c5934a85a09670b40b571774227c6bc"

      define_method(:install) do
        bin.install "symprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.2.0/symaira-print_0.2.0_linux_amd64.tar.gz"
      sha256 "3843f1e8ae2ca51c80f94056577257486c9b111a0d12a6591da8f1ab79cb807e"
      define_method(:install) do
        bin.install "symprint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.2.0/symaira-print_0.2.0_linux_arm64.tar.gz"
      sha256 "30bb858512e2da16744091c0905a5795d086f868c6925bb94ec966247bc15636"
      define_method(:install) do
        bin.install "symprint"
      end
    end
  end

  test do
    system "#{bin}/symprint", "version"
  end
end
