# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symprint < Formula
  desc "Markdown → beautiful PDF via named use-case profiles (Typst engine)"
  homepage "https://github.com/danieljustus/symaira-print"
  version "0.3.0"
  license "Apache-2.0"

  depends_on "typst"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.3.0/symaira-print_0.3.0_darwin_amd64.tar.gz"
      sha256 "1c477d8d8d698f07d880e616323fd5e7a1a76e13c3d1c2ebf5f4f39ad0a639fa"

      define_method(:install) do
        bin.install "symprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.3.0/symaira-print_0.3.0_darwin_arm64.tar.gz"
      sha256 "d3bd02446968b6b0b3bd45059cb36cf18f00e1cd26434fb30fcd44b367d1e167"

      define_method(:install) do
        bin.install "symprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.3.0/symaira-print_0.3.0_linux_amd64.tar.gz"
      sha256 "a6742b8cc2b633faeef23a2057af2d515352684e5e1997d943df0e017ec94422"
      define_method(:install) do
        bin.install "symprint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-print/releases/download/v0.3.0/symaira-print_0.3.0_linux_arm64.tar.gz"
      sha256 "5c48286ac75c129659dfe5bf4ef5c64c48729098ddc795d624ab0f6a36c0204e"
      define_method(:install) do
        bin.install "symprint"
      end
    end
  end

  test do
    system "#{bin}/symprint", "version"
  end
end
