# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symscope < Formula
  desc "Cross-platform port inventory and MCP discovery tool for AI agents"
  homepage "https://github.com/danieljustus/symaira-scope"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.2/symaira-scope_0.3.2_darwin_amd64.tar.gz"
      sha256 "aabc628098f54f54e0d583099d7ae5771cd727fda66231b8f221cc2854bb5137"

      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.2/symaira-scope_0.3.2_darwin_arm64.tar.gz"
      sha256 "0f7f01210807adb41494001a00e5a4874c859000edf6bdf0def63a9f2308d816"

      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.2/symaira-scope_0.3.2_linux_amd64.tar.gz"
      sha256 "968cd76f2191f687b0d11c7c357deade8828b9613c8c66c30a544157a43b2323"
      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.2/symaira-scope_0.3.2_linux_arm64.tar.gz"
      sha256 "f159c091ac60deaa6f02dd7c12ed6d437577506d3037e56d27c41bd8332807ea"
      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  test do
    system "#{bin}/symscope", "version"
  end
end
