# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symseek < Formula
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"
  version "2.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_darwin_amd64.tar.gz"
      sha256 "0d690a4b06c798b25dde13b331d7515ae6910923884d8a943d56f5ea89f71c0b"

      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_darwin_arm64.tar.gz"
      sha256 "06de8091f1998358e9fec335db79c9ff86ef6d6a6e73e23e32f3d892ecb36f04"

      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_linux_amd64.tar.gz"
      sha256 "b696f4bb2e61b6c3b3c4953f49432ae68c7770569aa22cd0f8045adb1f356180"
      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_linux_arm64.tar.gz"
      sha256 "38110f040a4b124f52964c9ca340137bfe74b4b860c617c61e51b44694ce2d84"
      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  service do
    run "#{opt_bin}/symseek"
  end

  test do
    system "#{bin}/symseek", "version"
  end
end
