# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symskills < Formula
  desc "Portable Skill SSOT manager for local AI agent harnesses"
  homepage "https://github.com/danieljustus/symaira-skills"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.1.2/symaira-skills_0.1.2_darwin_amd64.tar.gz"
      sha256 "18ef937bf468e0ed0237148e4c9763f4ea5a4caa0074a65f657272ec0502b2ab"

      define_method(:install) do
        bin.install "symskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.1.2/symaira-skills_0.1.2_darwin_arm64.tar.gz"
      sha256 "c3ebd69366f25439cebb2e637eebf206c79c9051270d008908f3b4b79e110732"

      define_method(:install) do
        bin.install "symskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.1.2/symaira-skills_0.1.2_linux_amd64.tar.gz"
      sha256 "08970e5928770427170171e5f4dfb79263567261eca6c9c44a0ad39254259970"
      define_method(:install) do
        bin.install "symskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.1.2/symaira-skills_0.1.2_linux_arm64.tar.gz"
      sha256 "4886580a09bdc8b3f442140557190346ee2bffffa75c336c789697e65f526fbb"
      define_method(:install) do
        bin.install "symskills"
      end
    end
  end

  test do
    system "#{bin}/symskills", "version"
  end
end
