# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symseek < Formula
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"
  version "2.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_darwin_amd64.tar.gz"
      sha256 "7f4bcaedfa460b24a685332f07a3f55bd6ffc7abaa5f64c3673498e670bd35b8"

      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_darwin_arm64.tar.gz"
      sha256 "c816dd536db308fbce1966cc62206264ca8fb59c7715c42bc8234fa3c1098ecf"

      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_linux_amd64.tar.gz"
      sha256 "3a88ab54b9f8836af2121e670eabb8814a421cccb4276a0fb5edd887072cd586"
      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.3.3/symaira-seek_2.3.3_linux_arm64.tar.gz"
      sha256 "826adae2df9e129e8271931c0065616c3a5a81863a1a26e17769059f14cb038a"
      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  service do
    run "#{opt_bin}/symseek"
  end

  test do
    system "#{bin}/symseek", "version"
  end
end
