# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symseek < Formula
  desc "Local-first, CGO-free document retrieval for AI agents"
  homepage "https://github.com/danieljustus/symaira-seek"
  license "Apache-2.0"

  disable! date: "2026-08-24", because: "absorbed into symaira-desktop (symdesk)"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.6.1/symaira-seek_2.6.1_darwin_amd64.tar.gz"
      sha256 "78e5f669d20f4d7db776b02e066ae38a12e02cf5ffdc858aa1e19a1deebd8d06"

      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.6.1/symaira-seek_2.6.1_darwin_arm64.tar.gz"
      sha256 "0381fd2d55ca5b91ef1c5592a443e12d79d8bd9d863741f82acde543e7ee59d1"

      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.6.1/symaira-seek_2.6.1_linux_amd64.tar.gz"
      sha256 "48c50d922a3b5d8432b57113325f334992b432aed001fd4a2f0846cd7d431192"
      define_method(:install) do
        bin.install "symseek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-seek/releases/download/v2.6.1/symaira-seek_2.6.1_linux_arm64.tar.gz"
      sha256 "ffe3f2df127cbd9c62d94369e54d59b5123a6c2500e9f95db43d60349e4ac0c5"
      define_method(:install) do
        bin.install "symseek"
      end
    end
  end

  service do
    run "#{opt_bin}/symseek"
  end

  test do
    system "#{bin}/symseek", "version"
  end
end
