# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symscope < Formula
  desc "Cross-platform port inventory and MCP discovery tool for AI agents"
  homepage "https://github.com/danieljustus/symaira-scope"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.2.0/symaira-scope_0.2.0_darwin_amd64.tar.gz"
      sha256 "64d9002815c4d9d7809cc4bb8f16735b1d5f5a6d21181628c897dd90f2dce1bb"

      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.2.0/symaira-scope_0.2.0_darwin_arm64.tar.gz"
      sha256 "f0a32806a2d01c56a91e2754c05e589a1c8e8cbb1904959208fef6d2704e0554"

      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.2.0/symaira-scope_0.2.0_linux_amd64.tar.gz"
      sha256 "d8ca0aa4a5cc30789274e980672d0ba003076f77710b7ff5fd29ad3aaeb336cc"
      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.2.0/symaira-scope_0.2.0_linux_arm64.tar.gz"
      sha256 "1262a86eb9a1456eb565cf90b63778dc29382d9d88100b96ca21741ae811d0ca"
      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  test do
    system "#{bin}/symscope", "version"
  end
end
