# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symskills < Formula
  desc "Portable Skill SSOT manager for local AI agent harnesses"
  homepage "https://github.com/danieljustus/symaira-skills"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.3.0/symaira-skills_0.3.0_darwin_amd64.tar.gz"
      sha256 "8d0863b4565d608d1835ef7987a246dff3e9d408764e17eb13e25e646dad4708"

      define_method(:install) do
        bin.install "symskills"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.3.0/symaira-skills_0.3.0_darwin_arm64.tar.gz"
      sha256 "491c1b36c006da05005a3f1f9410a57472742a30ca935482e324f7265d3d0abd"

      define_method(:install) do
        bin.install "symskills"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.3.0/symaira-skills_0.3.0_linux_amd64.tar.gz"
      sha256 "cd72948e17acaa7a90d7f27760ee7917f487f1aa0f094500515a142dd47fd426"
      define_method(:install) do
        bin.install "symskills"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-skills/releases/download/v0.3.0/symaira-skills_0.3.0_linux_arm64.tar.gz"
      sha256 "67c86fdc7616d672bd52bee91cb8dde054984c1e3a9dd4a48079211cc9657dee"
      define_method(:install) do
        bin.install "symskills"
      end
    end
  end

  test do
    system "#{bin}/symskills", "version"
  end
end
