# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symscope < Formula
  desc "Cross-platform port inventory and MCP discovery tool for AI agents"
  homepage "https://github.com/danieljustus/symaira-scope"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.1/symaira-scope_0.3.1_darwin_amd64.tar.gz"
      sha256 "641f78f49c124dd879954455e46de1d5be440a1fed3d3b1f360ec107628b4c4f"

      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.1/symaira-scope_0.3.1_darwin_arm64.tar.gz"
      sha256 "8629455cf5f09ed9021622596a870113d01c86079a28fd184b2b9d72ddba32db"

      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.1/symaira-scope_0.3.1_linux_amd64.tar.gz"
      sha256 "1a5d4ed4770c2f5bdab76901cba5dc769b5d86ef608ebaf18d72453e8a459a1a"
      define_method(:install) do
        bin.install "symscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-scope/releases/download/v0.3.1/symaira-scope_0.3.1_linux_arm64.tar.gz"
      sha256 "c2096d18946776da04c111d88fbbf13c9df2a54752b9d7b1c0a5079c42f3caeb"
      define_method(:install) do
        bin.install "symscope"
      end
    end
  end

  test do
    system "#{bin}/symscope", "version"
  end
end
