# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvibe < Formula
  desc "Graphical Vibe-Coding Baukasten that drives opencode"
  homepage "https://github.com/danieljustus/symaira-vibecoder"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.11.0/symvibe_0.11.0_darwin_amd64.tar.gz"
      sha256 "b22d438b3bd50c3f9dd65f7c795c7c4699c96f84c373e68b0aac7a94e33e9f1b"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.11.0/symvibe_0.11.0_darwin_arm64.tar.gz"
      sha256 "22ae4dea3622b7431fdeac822394445989382bf736ccfe41c8cf72ec3c79e2f0"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.11.0/symvibe_0.11.0_linux_amd64.tar.gz"
      sha256 "afa2524695e0c5a245f0bed1841c072c82051757e980cef2b3c2c86cfc0bcc8e"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.11.0/symvibe_0.11.0_linux_arm64.tar.gz"
      sha256 "80e50c3976d6b30ef88b9e7a47951da2d4b3b8843632564e5581d78b37439745"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  test do
    system "#{bin}/symvibe", "version"
  end
end
