# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvault < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/symaira-vault"
  version "0.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.10.0/symaira-vault_0.10.0_darwin_amd64.tar.gz"
      sha256 "8c8e27dab2222d60ce4c145fd345da83d634d8f7149c9a69dcd625df2b5ec19d"

      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.10.0/symaira-vault_0.10.0_darwin_arm64.tar.gz"
      sha256 "c4b47df16dcb43dce812f382e9e783870836eace2b78f00480e41c75f3f802bc"

      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.10.0/symaira-vault_0.10.0_linux_amd64.tar.gz"
      sha256 "7656eb5fe0cf236c912f3ab509f6db85d4bf75f200402c5f8bf1ca9e3727b2ad"
      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.10.0/symaira-vault_0.10.0_linux_arm64.tar.gz"
      sha256 "afe63fec4b680e08637ad3d4473ca8fd1d5b1b93d2bb677751f71974465a5d97"
      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  version_scheme 1

  def caveats
    <<~EOS
      Symaira Vault has been installed!

      To get started:
        symvault init                    # Initialize a new vault
        symvault set github.com/username # Add your first entry
        symvault get github.com/username # Retrieve it

      For MCP server setup:
        symvault mcp-config <name>

      The legacy openpass command remains available as a compatibility alias.

      Documentation: https://github.com/danieljustus/symaira-vault#readme
    EOS
  end

  test do
    system "#{bin}/symvault", "version"
    system "#{bin}/openpass", "version"
  end
end
