# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvault < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/symaira-vault"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.7.1/symaira-vault_0.7.1_darwin_amd64.tar.gz"
      sha256 "aef35e09542ed6971c0712af3d2ac1d092507b3925bfd9f8dc43ee84ea412cb7"

      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.7.1/symaira-vault_0.7.1_darwin_arm64.tar.gz"
      sha256 "c89181d68df18b9344dc78246f003b2ad3eea3223b8484f5b29c47b1a2985cb8"

      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.7.1/symaira-vault_0.7.1_linux_amd64.tar.gz"
      sha256 "66d429829b3c08cade40a3bc6df1579cc8d1e2ce62f8da08392d1c9dbb533fcc"
      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.7.1/symaira-vault_0.7.1_linux_arm64.tar.gz"
      sha256 "8d3e31dcf97afa088d7b78e1215ccbe44963ab8e7b3ab164267bc6660c79a8d5"
      define_method(:install) do
        bin.install "symvault"
        bin.install_symlink "symvault" => "openpass"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  version_scheme 1

  def caveats
    <<~EOS
      Symaira Vault has been installed!

      To get started:
        symvault init                    # Initialize a new vault
        symvault set github.com/username # Add your first entry
        symvault get github.com/username # Retrieve it

      For MCP server setup:
        symvault mcp-config <name>

      The legacy openpass command remains available as a compatibility alias.

      Documentation: https://github.com/danieljustus/symaira-vault#readme
    EOS
  end

  test do
    system "#{bin}/symvault", "version"
    system "#{bin}/openpass", "version"
  end
end
