# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvibe < Formula
  desc "Graphical Vibe-Coding Baukasten that drives opencode"
  homepage "https://github.com/danieljustus/symaira-vibecoder"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.6.0/symvibe_0.6.0_darwin_amd64.tar.gz"
      sha256 "c5c59ce6ad185895afc2e3ffd368c807aa0148db2d66b1057fcfbf6a10f49b19"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.6.0/symvibe_0.6.0_darwin_arm64.tar.gz"
      sha256 "18baa0dbda6d8278fff90bd3507cfa8d3bdb3c2d080bcf1c3acdd70a8f157e0c"

      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.6.0/symvibe_0.6.0_linux_amd64.tar.gz"
      sha256 "53bb6b00581ff70a7947d149bd3f014ad6754100defcfc17067e214cec6c2427"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vibecoder/releases/download/v0.6.0/symvibe_0.6.0_linux_arm64.tar.gz"
      sha256 "39882a295dc8c52f4e6307e659f60ecdf27a8fccbf8de4cac40ed8a61d58b5a8"
      define_method(:install) do
        bin.install "symvibe"
      end
    end
  end

  test do
    system "#{bin}/symvibe", "version"
  end
end
