# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Symvault < Formula
  desc "Modern CLI password manager with age encryption"
  homepage "https://github.com/danieljustus/symaira-vault"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.18.0/symaira-vault_0.18.0_darwin_amd64.tar.gz"
      sha256 "50375b1b0431d23848b9b5580cf82a4f4437f139ee0810f5c0f5a601dc5294bc"

      define_method(:install) do
        bin.install "symvault"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.18.0/symaira-vault_0.18.0_darwin_arm64.tar.gz"
      sha256 "a7a9312a35e250747f12d57ea591c71131facd0c51762f1274a9efc24953b0b9"

      define_method(:install) do
        bin.install "symvault"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.18.0/symaira-vault_0.18.0_linux_amd64.tar.gz"
      sha256 "afe90505f70fca9af469042af22a9f373cc7dbfa970895aabd480d1616160900"
      define_method(:install) do
        bin.install "symvault"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/danieljustus/symaira-vault/releases/download/v0.18.0/symaira-vault_0.18.0_linux_arm64.tar.gz"
      sha256 "89f700997cc53120a71ceadf3d55285c54445513d4d81d560a679c8062001843"
      define_method(:install) do
        bin.install "symvault"
        generate_completions_from_executable(bin/"symvault", "completion")
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  version_scheme 1

  def caveats
    <<~EOS
      Symaira Vault has been installed!

      To get started:
        symvault init                    # Initialize a new vault
        symvault set github.com/username # Add your first entry
        symvault get github.com/username # Retrieve it

      For MCP server setup:
        symvault mcp-config <name>

      Documentation: https://github.com/danieljustus/symaira-vault#readme
    EOS
  end

  test do
    system "#{bin}/symvault", "version"
  end
end
